show_downloads: false
google_analytics: UA-188438546-1

defaults:
  -
    scope:
      path: "**/*.md"
      type: "pages"
    values:
      article: true
  -
    scope:
      path: "plugins/**/*.html"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "examples/**/*.html"
      type: "pages"
    values:
      layout: "default"
